version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - .:/ec_coolie
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  bundle:
  db:
